In [1]:
import torch

In [4]:
ft = torch.FloatTensor([[1,2],[3,4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [7]:
lt = torch.LongTensor([[1,2],[3,4]])
lt.shape

torch.Size([2, 2])

In [8]:
import numpy as np

In [13]:
x = np.array([[1,2],[3,4]])
x.shape

(2, 2)

In [19]:
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>


In [20]:
x = x.numpy()
x

array([[1, 2],
       [3, 4]])

## Casting

In [22]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [23]:
lt.float()

tensor([[1., 2.],
        [3., 4.]])

In [24]:
print(lt.shape)

torch.Size([2, 2])


In [25]:
lt.shape

torch.Size([2, 2])

In [27]:
print(lt.size(1))

2


In [28]:
print(lt.size(-1))

2


In [32]:
W = torch.FloatTensor([[1,2],[3,4],[5,6]])
W.shape
b = torch.FloatTensor([2,2])

In [33]:
print(W.size())
print(b.size())

torch.Size([3, 2])
torch.Size([2])


In [34]:
def linear(x,W,b):
    y = torch.matmul(x,W) + b
    return y

x = torch.FloatTensor([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
x

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])

In [36]:
y = linear(x,W,b)
y

tensor([[11., 14.],
        [20., 26.],
        [29., 38.],
        [38., 50.]])

## nn.Module

In [37]:
import torch.nn as nn

In [38]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3,output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)
        
    def forward(self, x):
        y = torch.matmul(x, self.W) + self.b
        return y
    
linear = MyLinear(3,2)
y = linear(x)
y

tensor([[1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.]])

In [40]:
y.size()

torch.Size([4, 2])