In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
train_data = 'you need to know how to code'
word_set = set(train_data.split()) # set () : 중괄호를 사용하는 것이 Dictionary 와 유사, but 값이 없음, 중복이 제거됨 
word_set

{'code', 'how', 'know', 'need', 'to', 'you'}

In [3]:
vocab = {token: i for i, token in enumerate(word_set)} # enumerate : 반복문 사용 시 몇 번째 반복문인지 확인이 필요 , (index , value) 반환
vocab

{'how': 0, 'know': 1, 'code': 2, 'you': 3, 'need': 4, 'to': 5}

In [4]:
vocab2 = {}
for i, token in enumerate(word_set):
    vocab2[token] = i

vocab2

{'how': 0, 'know': 1, 'code': 2, 'you': 3, 'need': 4, 'to': 5}

In [5]:
len(vocab)

6

In [6]:
embedding_layer = nn.Embedding(num_embeddings = len(vocab),   
                               embedding_dim = 3)            
## num_embeddings  : 임베딩을 할 단어들의 개수 
## embedding_dim : 임베딩 벡터의 차원 (지정)
                                                 

In [7]:
lookup_tensor = torch.tensor([vocab['code']], dtype=torch.long)

In [8]:
lookup_tensor

tensor([2])

In [9]:
w = embedding_layer(lookup_tensor)

In [10]:
w

tensor([[-0.7122,  0.5291, -0.2349]], grad_fn=<EmbeddingBackward>)

In [11]:
embedding_layer.weight

Parameter containing:
tensor([[ 0.8374, -0.7984,  1.8893],
        [-0.3443,  0.0564, -0.8094],
        [-0.7122,  0.5291, -0.2349],
        [ 0.9541,  1.1322,  1.9058],
        [-1.1677,  1.2505,  1.1721],
        [ 1.5299,  0.6503,  0.6747]], requires_grad=True)

In [13]:
lookup_tensor2 = torch.tensor([vocab['you'], vocab['need'], vocab['code']], dtype=torch.long)
w = embedding_layer(lookup_tensor2)

In [14]:
w

tensor([[ 0.9541,  1.1322,  1.9058],
        [-1.1677,  1.2505,  1.1721],
        [-0.7122,  0.5291, -0.2349]], grad_fn=<EmbeddingBackward>)